package org.github.cyterdan.chat_over_kafka.data

import android.content.Context
import android.util.Log
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json

/**
 * Kafka configuration loaded from assets/kafka_config.json
 * This file is generated by the provisioning script for each user.
 */
@Serializable
data class KafkaConfig(
    val brokerUrl: String,
    val channels: List<ChannelConfig>,
    val certificates: CertificateConfig
) {
    @Serializable
    data class ChannelConfig(
        val channelNumber: Int,
        val channelName: String,
        val audioTopic: String,
        val audioPartition: Int,
        val metadataTopic: String,
        val metadataPartition: Int
    )

    @Serializable
    data class CertificateConfig(
        val caAssetName: String,
        val clientKeyAssetName: String,
        val clientCertAssetName: String
    )

    companion object {
        private const val TAG = "KafkaConfig"
        private const val CONFIG_FILE = "kafka_config.json"

        private val json = Json { ignoreUnknownKeys = true }

        /**
         * Load Kafka configuration from assets.
         * Returns null if config file is not found or invalid.
         */
        fun loadFromAssets(context: Context): KafkaConfig? {
            return try {
                val configJson = context.assets.open(CONFIG_FILE).bufferedReader().use { it.readText() }
                json.decodeFromString<KafkaConfig>(configJson).also {
                    Log.i(TAG, "Loaded config: broker=${it.brokerUrl}, channels=${it.channels.size}")
                }
            } catch (e: Exception) {
                Log.e(TAG, "Failed to load kafka_config.json: ${e.message}")
                null
            }
        }

        /**
         * Returns a default/fallback config for development.
         * Uses placeholder values that won't work without proper provisioning.
         */
        fun getDefaultConfig(): KafkaConfig {
            Log.w(TAG, "Using default config - app needs to be provisioned!")
            return KafkaConfig(
                brokerUrl = "kafka-3d4cc248-chat-over-kafka.f.aivencloud.com:16214",
                channels = listOf(
                    ChannelConfig(
                        channelNumber = 1,
                        channelName = "Main",
                        audioTopic = "chok-audio-1",
                        audioPartition = 0,
                        metadataTopic = "chok-metadata-1",
                        metadataPartition = 0
                    )
                ),
                certificates = CertificateConfig(
                    caAssetName = "ca.pem",
                    clientKeyAssetName = "client.key",
                    clientCertAssetName = "client.pem"
                )
            )
        }
    }
}
